image: continuumio/miniconda3

tasks:
  - init: |
      # https://github.com/ContinuumIO/docker-images/issues/151
      conda config --prepend pkgs_dirs $HOME/.conda/pkgs
      conda env create -f environment.yml
    command: conda activate aspi
